name: test

on:
  workflow_call:
    inputs:
      should_push:
        required: false
        type: string
        default: 'true'
      source_ref:
        required: false
        type: string
        default: 'main'
      build_path:
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ inputs.source_ref }}

      - name: Build image
        id: build
        run: |
          set -a
          . ./build/${{ inputs.build_path }}/.env
          set +a
          echo "image_name=$IMAGE_NAME" >> "$GITHUB_OUTPUT"
          echo "Building Docker image with Dockerfile..."
          bash ./build/${{ inputs.build_path }}/docker-build.sh Dockerfile ./build/${{ inputs.build_path }}

      - name: Run tests
        run: |
          bash ./build/${{ inputs.build_path }}/docker-test.sh ./build/${{ inputs.build_path }}

      - name: Save Docker image as artifact
        if: inputs.should_push == 'true'
        run: |
          set -a
          . ./build/${{ inputs.build_path }}/.env
          set +a
          docker save "$IMAGE_NAME" > "$IMAGE_NAME.tar"

      - name: Upload Docker image artifact
        if: inputs.should_push == 'true'
        uses: actions/upload-artifact@v6
        with:
          name: docker-image-${{ steps.build.outputs.image_name }}
          path: ${{ steps.build.outputs.image_name }}.tar
          retention-days: 1